Repin for Bazel if needed in Build step
dfinity/dre pull request #174
Opened 2024-02-08 16:29 UTC by pietrodimarco-dfinity

2024-02-08 17:17 UTC, sasa-tomic commented on .github/workflows/main.yaml
> +              build_output=$(bazel build ... 2>&1)
The changed lock files still need to be pushed back to the branch, or shall we do that in a follow up?

2024-02-08 17:37 UTC, DFINITYManu commented on .github/workflows/main.yaml
> +          build_output=$(bazel build ... 2>&1)
You must actually output this, not just swallow it.

Here is a way you can do this properly:

```
MYTMPDIR="$(mktemp -d)"
trap 'rm -rf -- "$MYTMPDIR"' EXIT
r=0
logfile="$MYTMPDIR/bazel-out.log"
bazel build ... 2>&1 | tee "$logfile" >&2 || r=?
if [ "$r" != 0 ]; then
    if grep -q 'Digests do not match" "$logfile" ; then
        export CARGO_BAZEL_REPIN=true
        bazel build ...
    else
        exit $r
    fi
fi
````

2024-02-08 17:38 UTC, DFINITYManu requested changes

2024-02-08 17:43 UTC, pietrodimarco-dfinity commented on .github/workflows/main.yaml
> +          build_output=$(bazel build ... 2>&1)
Thx :)

2024-02-09 09:09 UTC, NikolaMilosa commented on .github/workflows/build/action.yaml
> +        bazel_build_auto_repin build ...
I think its a bit lighter to use `query` for repinning, can we not use that?

2024-02-09 09:10 UTC, sasa-tomic approved these changes

2024-02-09 09:27 UTC, NikolaMilosa approved these changes
Noice!

2024-02-09 15:38 UTC, merged