Explain that the reproduction process is only important for GuestOS.
dfinity/dre pull request #999
Opened 2024-10-09 07:43 UTC by DFINITYManu

2024-10-10 09:38 UTC, LittleChimera requested changes
we probably want to hold this off until we have proper changes in place

2024-10-11 15:10 UTC, sasa-tomic requested changes

2024-10-11 15:10 UTC, sasa-tomic commented on release-controller/release_index_loader.py
> +The two SHA256 sums printed above from a) the downloaded CDN image and b) the locally built image, must be identical, and must match the SHA256 from the payload of the NNS proposal.  The verification
We have been discussing submitting both the HostOS and GuestOS proposal together on a weekly basis, so let's wait with merging this PR until we decide what to do on that matter.

2024-11-11 09:29 UTC, sasa-tomic commented
Implemented similar changes in https://github.com/dfinity/dre/pull/1028

2024-11-11 09:29 UTC, closed without merging